application: gae-python-cms
version: 1
runtime: python
api_version: 1

inbound_services:
- warmup

handlers:
- url: /assets
  static_dir: static

- url: /admin/.*
  script: admin.py
  login: admin

- url: /.*
  script: router.py

admin_console:
  pages:
  - name: Administrate GAE-Python-CMS
    url: /admin/